# These are Imri's default settings. you can change it for your preprocessing of a fixed fish.

FOCAL_LIM_X_MINUS = 70
FOCAL_LIM_X_PLUS = 70

FOCAL_LIM_Y_MINUS = 20
FOCAL_LIM_Y_PLUS = 90

HEAD_MASK_X_MINUS = 15
HEAD_MASK_X_PLUS = 15

HEAD_MASK_Y_MINUS = 20
HEAD_MASK_Y_PLUS = 30

TAIL_MASK_Y_LOWER = 15
TAIL_MASK_Y_UPPER = 90

HEAD_MASK_THRESHOLD = 150
IMG_BINARY_THRESHOLD = 18
FPS = 30

HEAD_DARKENING_PERIMETER = 300