name: closed_loop
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2020.10.14
  - certifi=2020.6.20
  - openssl=1.1.1h
  - pip=20.2.4
  - python=3.7.9
  - setuptools=50.3.1
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - screeninfo==0.8.1
    - psutil==5.9.0
    - nidaqmx==0.8.0
    - cycler==0.10.0
    - decorator==4.4.2
    - et-xmlfile==1.0.1
    - fpdf==1.7.2
    - imageio==2.9.0
    - joblib==0.17.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.2
    - matplotlib-scalebar==0.7.2
    - networkx==2.5
    - numpy==1.19.2
    - opencv-contrib-python-headless==4.5.4.60
    - opencv-contrib-python==4.5.4.60
    - openpyxl==3.1.2
    - pandas==1.3.5
    - pillow==8.0.1
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - pywavelets==1.1.1
    - scikit-image==0.17.2
    - scikit-learn==0.23.2
    - scipy==1.4.1
    - seaborn==0.11.1
    - six==1.15.0
    - threadpoolctl==2.1.0
    - tifffile==2020.10.1
    - tqdm==4.51.0
    - xlrd==2.0.1
    - xlsxwriter==1.4.0
    - h5py==3.8.0
    - pymatreader==0.0.32
    - moviepy==1.0.3
    - xmltodict==0.13.0
    - pyvista==0.38.6
    - spinnaker_python-2.6.0.156-cp37-cp37m-win_amd64.whl

